In [134]:
import pandas as pd
import numpy as np

In [186]:
# Carregando o 'dataset':
dataset = pd.read_csv('load_boston.csv')

In [175]:
# Verificando o tamanho do  'dataset':
dataset.shape

(506, 14)

In [136]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO   
0  0.00632  18.0   2.31     0  0.538  6.575  65.2   4.090    1  296     15.3  \
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  49.671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  49.671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  60.622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  60.622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [137]:
dataset['ZN'].unique()

array([ 18. ,   0. ,  12.5,  75. ,  21. ,  90. ,  85. , 100. ,  25. ,
        17.5,  80. ,  28. ,  45. ,  60. ,  95. ,  82.5,  30. ,  22. ,
        20. ,  40. ,  55. ,  52.5,  70. ,  34. ,  33. ,  35. ])

In [153]:
X = dataset
y = dataset

In [162]:
# Normalização dos dados:
from sklearn.preprocessing import StandardScaler

sS = StandardScaler()
X = sS.fit_transform(X)

In [163]:
# Saída dos dados normalizados:
X

array([[-0.5349917 ,  0.28482986, -1.2879095 , ...,  0.44105193,
        -1.0755623 ,  0.15968566],
       [-0.53490643, -0.48772236, -0.59338101, ...,  0.44105193,
        -0.49243937, -0.10152429],
       [-0.53490651, -0.48772236, -0.59338101, ...,  0.39642699,
        -1.2087274 ,  1.32424667],
       ...,
       [-0.53477054, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.98304761,  0.14880191],
       [-0.53457216, -0.48772236,  0.11573841, ...,  0.4032249 ,
        -0.86530163, -0.0579893 ],
       [-0.53482477, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.66905833, -1.15724782]])

In [164]:
# Separando os dados para testes e treinos:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [165]:
# Separação de X_tarain, y_train:
X_train.shape, y_train.shape

((379, 14), (379, 14))

In [166]:
# Separação do X_test, y_test:
X_test.shape, y_test.shape

((127, 14), (127, 14))

In [188]:
# Aplicando o Treinamento:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [190]:
# Predição dos dados treinados:
pred = reg.predict(X_test)

In [191]:
# Saida dos dados de predição:
pred

array([[ 6.72400000e-02, -7.10542736e-15,  3.24000000e+00, ...,
         3.75210000e+02,  7.34000000e+00,  2.26000000e+01],
       [ 9.23230000e+01, -3.55271368e-15,  1.81000000e+01, ...,
         3.66150000e+02,  9.53000000e+00,  5.00000000e+01],
       [ 1.14250000e-01, -3.73034936e-14,  1.38900000e+01, ...,
         3.93740000e+02,  1.05000000e+01,  2.30000000e+01],
       ...,
       [ 3.49400000e-01,  7.10542736e-15,  9.90000000e+00, ...,
         3.96240000e+02,  9.97000000e+00,  2.03000000e+01],
       [ 9.84900000e-02,  1.06581410e-14,  2.56500000e+01, ...,
         3.79380000e+02,  1.75800000e+01,  1.88000000e+01],
       [ 7.50300000e-02,  3.30000000e+01,  2.18000000e+00, ...,
         3.96900000e+02,  6.47000000e+00,  3.34000000e+01]])

In [192]:
# Verificando os dados treinados de 'y_test':
y_test

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX   
329    0.06724   0.0   3.24     0  0.460  6.333   17.2  52.146    4  430  \
371   92.32300   0.0  18.10     0  0.631  6.216  100.0  11.691   24  666   
219    0.11425   0.0  13.89     1  0.550  6.373   92.4  33.633    5  276   
403  248.01700   0.0  18.10     0  0.693  5.349   96.0  17.028   24  666   
78     0.05646   0.0  12.83     0  0.437  6.232   53.7  50.141    5  398   
..         ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
49     0.21977   0.0   6.91     0  0.448  5.602   62.0  60.877    3  233   
498    0.23912   0.0   9.69     0  0.585  6.019   65.3  24.091    6  391   
309    0.34940   0.0   9.90     0  0.544  5.972   76.7  31.025    4  304   
124    0.09849   0.0  25.65     0  0.581  5.879   95.8  20.063    2  188   
306    0.07503  33.0   2.18     0  0.472  7.420   71.9  30.992    7  222   

     PTRATIO       B  LSTAT  MEDV  
329     16.9  375.21   7.34  22.6  
371     20.2  366.15   9.53  50.0  
219     16.4  393.74  10.50  23.0  
403     20.2  396.90  19.77   8.3  
78      18.7  386.40  12.34  21.2  
..       ...     ...    ...   ...  
49      17.9  396.90  16.20  19.4  
498     19.2  396.90  12.92  21.2  
309     18.4  396.24   9.97  20.3  
124     19.1  379.38  17.58  18.8  
306     18.4  396.90   6.47  33.4  

[127 rows x 14 columns]

In [194]:
# Vericando a acuracia do modelo treinado:
from sklearn.metrics import mean_squared_error, mean_absolute_error
# Chamando a função:
mse = mean_squared_error(y_test, pred)
mae = mean_absolute_error(y_test, pred)


In [195]:
# Saida de 'mse':
mse

1.7319907930306724e-25

In [196]:
# Saída de 'mae':
mae

1.5209966262040848e-13