In [1]:
import numpy as np

In [2]:
# Criando os valores de 'X' e 'Y':
x = [21, 23, 27, 32, 34, 41, 50, 53, 57, 59, 38, 46, 48, 48, 60]                                    # Idades  
y = [1000, 1100, 1250, 1700, 1500, 1980, 2500, 3500, 2200, 4100, 3900, 5100, 5500, 7000, 6500]      # Sálarios

In [3]:
# Importando o modulo para criação do gráfico:
import plotly.express as px

In [4]:
# Representando em gráfico 'gra':
gra = px.scatter(x=x, y=y)
gra.show()

In [6]:
# Criando um array com os dados do gráfico:
base_salario = np.array([[21,1000], [23,1100], [27,1250], [32,1700], [34,1500], [38,3900], [41,1980], 
                        [46,5100], [48,5500], [48,7000], [50,2500], [53,3500], [57,2200], [59,4100], [60,6500]])


In [7]:
# Retorno da base_salario criada:
base_salario

array([[  21, 1000],
       [  23, 1100],
       [  27, 1250],
       [  32, 1700],
       [  34, 1500],
       [  38, 3900],
       [  41, 1980],
       [  46, 5100],
       [  48, 5500],
       [  48, 7000],
       [  50, 2500],
       [  53, 3500],
       [  57, 2200],
       [  59, 4100],
       [  60, 6500]])

In [9]:
# Importando o modulo para fazer a normalização dos dados:
from sklearn.preprocessing import StandardScaler

In [10]:
# chamando o modulo de importação:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)


In [11]:
# Retorno dos dados normalizados;
base_salario

array([[-1.72769059, -1.15955852],
       [-1.56672563, -1.10814445],
       [-1.24479571, -1.03102336],
       [-0.8423833 , -0.79966007],
       [-0.68141834, -0.9024882 ],
       [-0.35948842,  0.33144933],
       [-0.11804097, -0.65570069],
       [ 0.28437143,  0.9484181 ],
       [ 0.4453364 ,  1.15407435],
       [ 0.4453364 ,  1.92528531],
       [ 0.60630136, -0.38834756],
       [ 0.8477488 ,  0.12579308],
       [ 1.16967872, -0.54258975],
       [ 1.33064369,  0.43427746],
       [ 1.41112617,  1.66821499]])

In [12]:
# Importando o modulo 'k-means' para o treinamento dos dados:
from sklearn.cluster import KMeans

In [13]:
# Clusterização dos dados:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

C:\Users\heddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=3)

In [14]:
# Verificando as posições de cada centroides:
centroide = kmeans_salario.cluster_centers_

# Saída do 'centroide':
centroide

array([[-1.21260271, -1.00017492],
       [ 0.57947386, -0.11585302],
       [ 0.6465426 ,  1.42399818]])

In [15]:
# Verificando os dados da forma inversa:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  27.4       , 1310.        ],
       [  49.66666667, 3030.        ],
       [  50.5       , 6025.        ]])

In [16]:
# Definindo a classificação dos agrupamentos dos dados:
rotulos = kmeans_salario.labels_
rotulos

array([0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2])

In [18]:
# Importando o modulo para mostrar os graficos:
import plotly.graph_objects as go
# Visualizando no gráfico:
gra1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
gra2 = px.scatter(x = centroide[:,0], y = centroide[:,1], size=[8,8,8])
gra3 = go.Figure(data = gra1.data + gra2.data)
gra3.show()